export interface Ievent{
   id: number;
   FullName: string
   StudyNo : number
   HospitalNumber : string
   Gender : string
   DateOBirth : Date
   AgeAtFirstVisitToPNC : string
   EthnicGroup : string
   GeopoliticalZone : string
   WithWhomDoesChildLive : string
   Informant : string
   AnyChangeInCaregiverSinceDiagnosis : string
   IfYesWho : string
   Addreess : string
   StateofResidence : string
   PhoneNumber : string
   EmailAddress : string
   DateOfEnrolment : string
   DateFirstDiagnosedWithCerebralPalsy : string
   AgeAtWhichParentsFirstObservedDelaysInMilestones : string
   AgeAtDiagnosisOfCerebralPalsyInMonths : string
   WhoMadeTheDiagnosisOfCerebralPalsy : string
   SourceOfReferral : string
   


   PatternOfLimbInvolvment : string
   LimbsInvolved : string
   TypeOfCP : string
   IfSpasticIsItUnilateralOrBilateralSpasticCP : string
   GmfcsClass : string
   IsChildReceivingPhysiotherapy : string
   FrequencyOfPhysioSessions : string
   AgeAtCommencementOfPhysio : string
   DurarionOfPhysiotherapy : string
   AnyOrthopaedicInterventions : string
   IfYesTypeOfIntervention : string
   DoesChildHaveAnyAssistiveLocomotorDevice : string
   IfYesWhoProvidedIt : string
      
   duration_of_pregnancy : string
   Term_Preterm : string
   types_of_conception : string
   if_assisted_which_type : string
   complication_in_pregnancy : string
   IfYesGiveDetails : string
   country_of_birth : string
   type_of_pregnancy : string
   duration_of_labour : string
   mode_of_delivery : string
   vacuum_extraction : string
   place_of_delivery : string
   Did_he_or_she_cry_immediately_after_birth : string
   any_active_resuscitation_at_birth : string
   birth_weight : string
   time_to_first_feed_after_birth : string
   mode_of_feeding_after_birth : string
   Glucose_water : string
   any_NICU_admission : string
   reason_for_admission : string
   duration_of_NICU_admission : string
   any_history_of_neonatal_seizures : string
   any_history_of_NNJ : string
   If_yes_SBR_level : string
   treatment_given_for_NNJ : string
   any_history_suggestive_of_NN_Sepsis : string
   any_history_suggestive_of_NN_meningitis : string
   any_history_of_metabolic_disorder_or_derangement : string
   any_major_illnesses_in_the_past : string
   indication_for_hospital_admission : string
   age_at_illness : string
   duration_of_hospitalization : string
   was_admission_due_complication_of_CP : string
   was_admission_related_to_the_etiology_of_CP : string
   any_previous_ICU_admission : string
   risk_factor_of_CP : string
   risk_for_CP_identified : string
   cranial_MRI_CT_scan : string
   if_yes_give_results : string
   EEG : string
   if_yes_give_details : string
   severe_perinatal_asphyxia : string
   NN_meningitis : string
   Bilirubin_encephalopathy : string
   exposure_to_radiation : string
   intrauterine_infection : string
   NN_Sepsis : string
   Maternal_pregnancy_complication : string
   prolonged_rupture_of_membranes : string
   congenital_CNS_malformation : string
   any_other_congenital_malformation_state_type : string
   maternal_drug_or_alcohol_exposure_state_type_of_drug : string
   prematurity : string
   low_birth_weight : string
   traumatic_delivery : string
   intracranial_infection_metabolic_disorder_state_type : string
   metabolic_disorder_state_type : string
   traumatic_brain_injury : string
   hypoxic_brain_injury : string
   multi_Births : string
   stroke : string
   give_details : string
   any_other_state : string
   prenatal_or_perinatal_or_postnatal : string
   Presumed_cause_of_CP : string
   for_postnatal_Cp_state_age_at_brain_injury : string
   Does_a_child_have_a_comorbidities : string
   Has_child_received_visual_assesment_by_ophthalmologist : string
   Has_child_received_hearing_assessment : string
   Visual_impairment : string
   types_of_Visual_impairment : string
   hearing_impairment : string
   types_of_hearing_impairment : string
   epilepsy : string
   types_of_epilepsy : string
   speech_problems : string
   intellectual_disability : string
   Report_of_IQ_assessment : string
   Autism_spectrum_disorder : string
   ADHD : string
   behaviour_problems : string
   feeding_difficulties : string
   growth_impairment : string
   microcephaly : string
   head_circumference : string
   medication_list_if_any : string
   father_highest_level_of_education : string
   father_occupation : string
   mother__highest_level_of_education : string
   mother_occupation : string
   caregivers_if_not_parent_highest_level_of_education : string
   caregivers_occupation : string
   any_family_history_of_development_disorder_or_delay : string
   Is_child_enrolled_in_the_school : string
   types_of_school_not_school_age : string
   Has_child_ever_repeated_a_class : string
   immunisation_Status : string
   Do_parents_have_concern_about_child_growth_and_weight : string
   Do_parents_have_concern_about_childs_health : string
   Do_parents_have_concern_about_child_eating_pattern : string
   Does_child_take_longer_to_eat_milk_than_expected : string
   is_child_able_to_eat_and_drink_efficiently : string
   is_child_able_to_eat_and_drink_safely_without_choking : string
   Is_the_feeding_experience_pleasant_for_the_child_and_family : string
   Do_parent_have_to_prepare_food : string
   What_are_the_childs_preferred_foods_list_as_necessary : string
   Is_child_fluid_intake_adequate : string
   Is_urine_output_a_adequate : string
   Who_feeds_the_child_in_school : string
   Who_feeds_the_child_when_parents_are_unavailable : string
   How_is_child_positioned_for_feeding : string
   How_frequently_does_child_feed_in_a_day : string
   Does_this_child_have_difficulties_with_feeding : string
   if_yes_which_type_of_feeding_difficulties : string
   Is_this_child_able_to_feed_as_children_of_his_age : string
   drooling : string
   difficulty_with_swallowing : string
   choking_on_feeds : string
   Recurrent_aspiration : string
   refusal_of_feeds : string
   interest_in_some_food_types_only : string
   inability_to_chew : string
   Need_for_caregiver_assistance_to_feed : string
   if_there_concern_with_feeding : string
   how_does_illness_affect_childs_feeding : string
   Has_the_child_experience_episodes_of_weight_loss_for_dehydration : string
   does_the_child_take_any_caloric_protein_vitamins : string
   weight_today : string
   is_it_appropriate_for_age : string
   If_yes_what_was_the_measured_length_or_height : string
   Is_child_overweight_observe : string
   Does_child_have_any_sign_of_faltering_growth : string
   Did_caregiver_receive_any_special_education_from_the_health_care : string
   has_child_ever_been_admitted_for_nutritional_rehabilitation : string
   Has_child_been_admitted_at_any_time_in_the_hospital : string
   if_yes_indication_for_admission_health_facility_and_duration : string
   OFC_cm : string
   age_OFC_cm : string
   MUAC_cm : string
   age_MUAC_cm : string
   height_or_length : string
   age_height_or_length : string
   weight : string
   age_weight : string
   ulnar_length : string
   age_ulnar_length : string
   chest_circumference : string
   age_chest_circumference : string
   ofc_or_cc_ratio : string
   age_ofcc_or_cc : string
   z_score_weight : string
   hair_colour : string
   hair_texture : string
   date_last_seen_in_the_PNC : string
   age_at_last_visit_to_PNC : string
   total_duration_of_follow_up : string
   total_number_of_clinic_visits : string
   Help_the_child_attended_the_PNC_in_the_last_one_year : string
   Has_the_child_attended_the_pins_in_the_last_6_months : string
   None : string
   neck_control : string
   independent_sitting : string
   crawling : string
   walking_with_Assistant : string
   independent_walking : string
   running : string
   independent_climbing : string
   other_Sporting_activities : string
   telephone_contact_reached_on_phone : string
   if_reached_phone_number : string
   Alive_lives_with_parents : string
   Alive_lives_in_an_industrial_home : string
   Alive_lives_with_relation : string
   Dead : string
   state_age_at_death : string
   independence_of_caregiver_assistance_for_daily_living : string
   Required_assistant_for_daily_living : string
   completely_dependent_on_caregiver_assistance : string
   
}